
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  topology:
    class: example-clusterclass
    version: v1.27.3
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: example-worker
        name: ${CLUSTER_NAME}-machine
        replicas: 2
