apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: baremetal
          name: '{{ ds.meta_data.hostname }}'
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: test1-md-metadata
  namespace: default
spec:
  clusterName: test1
  metaData:
    fromHostInterfaces:
    - interface: eth0
      key: mac
    gatewaysFromIPPool:
    - key: gateway_1
      name: pool1
    - key: gateway_2
      name: pool2
    - key: gateway6_1
      name: pool6-1
    - key: gateway6_2
      name: pool6-2
    indexes:
    - key: index_0_1
      offset: 0
      step: 1
    - key: index_3
      offset: 3
    - key: index_5_2
      offset: 5
      step: 2
    ipAddressesFromIPPool:
    - key: ip_1
      name: pool1
    - key: ip_2
      name: pool2
    - key: ip6_1
      name: pool6-1
    - key: ip6_2
      name: pool6-2
    objectNames:
    - key: machine_name
      object: machine
    - key: metal3machine_name
      object: metal3machine
    - key: bmh_name
      object: baremetalhost
    prefixesFromIPPool:
    - key: prefix_1
      name: pool1
    - key: prefix_2
      name: pool2
    - key: prefix6_1
      name: pool6-1
    - key: prefix6_2
      name: pool6-2
    strings:
    - key: abc
      value: def
  networkData:
    links:
      ethernets:
      - id: enp1s0
        macAddress:
          fromHostInterface: eth0
        type: phy
      - id: enp2s0
        macAddress:
          fromHostInterface: eth1
        type: phy
    networks:
      ipv4:
      - id: baremetal
        ipAddressFromIPPool: pool1
        link: enp2s0
        routes:
        - gateway:
            fromIPPool: pool1
          network: 0.0.0.0
          prefix: 0
          services:
            dns:
            - 8.8.4.4
      ipv4DHCP:
      - id: provisioning
        link: enp1s0
    services:
      dns:
      - 8.8.8.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test1-md-0
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: test1-md-metadata
      image:
        checksum: http://172.22.0.1/images/UBUNTU_22.04_NODE_IMAGE_K8S_v1.29.0-raw.img.sha256sum
        checksumType: sha256
        format: raw
        url: http://172.22.0.1/images/UBUNTU_22.04_NODE_IMAGE_K8S_v1.29.0-raw.img
