apiVersion: v1
data:
  password: MWYyZDFlMmU2N2Rm
  username: YWRtaW4=
kind: Secret
metadata:
  name: demo-externally-provisioned-secret
  namespace: default
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-0
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.10:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-0
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f1e
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-1
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: redfish+http://192.168.111.1:8000/redfish/v1/Systems/0a2e3d8c-e230-4511-845a-ccb12e0b71f4
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-1
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f10
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-2
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.12:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-2
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f11
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-3
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.13:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-3
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f12
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-4
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.14:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-4
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f13
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-5
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.15:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-5
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f14
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-6
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: redfish+http://192.168.111.1:8000/redfish/v1/Systems/0a2e3d8c-e230-4511-845a-ccb12e0b71f5
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-6
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f15
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-7
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.17:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-7
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f16
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-8
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.18:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-8
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f17
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: metal3-9
  namespace: default
spec:
  automatedCleaningMode: metadata
  bmc:
    address: ipmi://192.168.122.19:6233
    credentialsName: demo-externally-provisioned-secret
  bootMode: legacy
  online: true
status:
  errorCount: 0
  errorMessage: ""
  goodCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
  hardware:
    cpu:
      arch: x86_64
      clockMegahertz: 2494.222
      count: 4
      flags:
      - aes
      model: Intel Xeon E3-12xx v2 (Ivy Bridge)
    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1
    hostname: metal3-9
    nics:
    - ip: 172.22.0.11
      mac: 00:28:19:1f:79:4d
      model: 0x1af4 0x0001
      name: eth0
      pxe: true
      speedGbps: 0
      vlanId: 0
    - ip: 192.168.111.20
      mac: 00:28:19:1f:79:4f
      model: 0x1af4 0x0001
      name: eth1
      pxe: false
      speedGbps: 0
      vlanId: 0
    ramMebibytes: 8192
    storage:
    - hctl: "6:0:0:0"
      model: QEMU HARDDISK
      name: /dev/sda
      rotational: true
      serialNumber: drive-scsi0-0-0-0
      sizeBytes: 53687091200
      type: HDD
      vendor: QEMU
    systemVendor:
      manufacturer: QEMU
      productName: Standard PC (Q35 + ICH9, 2009)
      serialNumber: ""
  hardwareProfile: unknown
  operationHistory: {}
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: be02cfb3-7b24-47c7-b9b8-d69207d86f18
    bootMode: legacy
    image:
      checksum: http://172.22.0.1/images/centos-updated.qcow2.sha256sum
      url: http://172.22.0.1/images/centos-updated.qcow2
    rootDeviceHints:
      deviceName: /dev/sda
    state: ready
  triedCredentials:
    credentials:
      name: demo-externally-provisioned-secret
      namespace: default
    credentialsVersion: "879"
