
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  topology:
    class: example-clusterclass
    version: ${KUBERNETES_VERSION}
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: example-worker
        name: ${CLUSTER_NAME}-machine
        replicas: 2
    variables:
    - name: image
      value:
        checksum: ${IMAGE_CHECKSUM}
        checksumType: ${IMAGE_CHECKSUM_TYPE}
        format: ${IMAGE_FORMAT}
        url: ${IMAGE_URL}
    - name: controlPlaneEndpoint
      value:
        host: ${CLUSTER_APIENDPOINT_HOST}
        port: ${CLUSTER_APIENDPOINT_PORT}
