apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam-controller-manager
  namespace: capm3-system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: 192.168.111.1:5000/localimages/ip-address-manager:main
        name: manager